project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!presentations/*.md"
    - "!presentations/*/*.md"
  resources:
    - "presentations/data/*" 
    - "data/*"
    - "*.md"
    - "*.html"
    - "*.png"
    - "*.svg"

execute:
  freeze: auto  # re-render only when source changes
  cache: true

website:
  title: "NG data club"
  navbar:
    background: light
    left:
      - href: index.qmd
        text: Home
      - href: presentations/index.qmd
        text: Presentations
      - href: about.qmd
        text: About
    
format:
  html:
    theme: default
    toc: true